### DISCUSSION TITLE
Getting homestar (lenovo ideapad duet 5) audio to fully work

### DISCUSSION THREAD

**Discussion by thenameisluk** [velvet-os/imagebuilder#240] [Getting started]
while someone managed to find [a solution](https://github.com/hexdump0815/imagebuilder/issues/44#issuecomment-1913130004) it doesn't seam to be reproducible

there is [temporary solution](https://github.com/hexdump0815/imagebuilder/issues/68#issuecomment-2186001368) that makes only speakers on one side work

it is something 'm planning to look into myself but it seams a bit too difficult for me
if someone has more time/experience, any help with putting it together would be appreciated

a solution will (hopefully) be added below

**Comment by thenameisluk** [comment]
idk how but it somehow works
![Zrzut ekranu z 2024-09-19 09-04-29](https://github.com/user-attachments/assets/a92f4ec2-1db3-4e92-8889-d94efb268fa2)
will work on reproducing it

**Comment by thenameisluk** [comment]
## Simple solution
solution :
```
luk@backluk:~$ diff /usr/share/alsa/ucm2/Qualcomm/sc7180/rt5682-max98357a/HiFi.conf ~/Pobrane/HiFi.conf 
13c13
< 		PlaybackChannels 2 <- broken
---
> 		PlaybackChannels 4 <- works
```
just put [HiFi.conf](https://gitlab.com/-/project/8065375/uploads/ac23613adaf88501e0906a032d2f4b82/HiFi.conf) in ```/usr/share/alsa/ucm2/Qualcomm/sc7180/rt5682-max98357a/HiFi.conf```
<details>
<summary>file content</summary>

```
# Use case configuration for ALC5682+MAX98357A on SC7180

SectionVerb {
	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Speaker"

	Value {
		PlaybackChannels 4
		PlaybackPCM "hw:${CardId},1"
		PlaybackPriority 100
		PlaybackMixerElem "Speaker"
		PlaybackVolume "Speaker Playback Volume"
	}
}

SectionDevice."Headphones" {
	Comment "Headphones"

	EnableSequence [
		cset "name='HPOL Playback Switch' 1"
		cset "name='HPOR Playback Switch' 1"
		cset "name='Stereo1 DAC MIXL DAC L1 Switch' 1"
		cset "name='Stereo1 DAC MIXR DAC R1 Switch' 1"
	]

	DisableSequence [
		cset "name='HPOL Playback Switch' 0"
		cset "name='HPOR Playback Switch' 0"
		cset "name='Stereo1 DAC MIXL DAC L1 Switch' 0"
		cset "name='Stereo1 DAC MIXR DAC R1 Switch' 0"
	]

	Value {
		PlaybackPCM "hw:${CardId},0"
		PlaybackPriority 200
		PlaybackMasterElem "DAC1"
		PlaybackMixerElem "Headphone"
		PlaybackVolume "Headphone Playback Volume"
	}
}

SectionDevice."Mic" {
	Comment "Internal Microphone"

	ConflictingDevice [
		"Headset"
	]

	EnableSequence [
		cset "name='IF1 01 ADC Swap Mux' 1"
		cset "name='Stereo1 ADC L2 Mux' 1"
		cset "name='Stereo1 ADC R2 Mux' 1"
		cset "name='Stereo1 ADC MIXL ADC2 Switch' 1"
		cset "name='Stereo1 ADC MIXR ADC2 Switch' 1"
	]

	DisableSequence [
		cset "name='Stereo1 ADC L2 Mux' 0"
		cset "name='Stereo1 ADC R2 Mux' 0"
		cset "name='Stereo1 ADC MIXL ADC2 Switch' 0"
		cset "name='Stereo1 ADC MIXR ADC2 Switch' 0"
	]

	Value {
		CapturePCM "hw:${CardId},0"
		CapturePriority 100
		CaptureMixerElem "STO1 ADC"
		CaptureVolume "STO1 ADC Capture Volume"
	}
}

SectionDevice."Headset" {
	Comment "Headset Microphone"

	EnableSequence [
		cset "name='IF1 01 ADC Swap Mux' 2"
		cset "name='Stereo1 ADC L1 Mux' 1"
		cset "name='Stereo1 ADC R1 Mux' 1"
		cset "name='Stereo1 ADC MIXL ADC1 Switch' 1"
		cset "name='Stereo1 ADC MIXR ADC1 Switch' 1"
	]

	DisableSequence [
		cset "name='Stereo1 ADC L1 Mux' 0"
		cset "name='Stereo1 ADC R1 Mux' 0"
		cset "name='Stereo1 ADC MIXL ADC1 Switch' 0"
		cset "name='Stereo1 ADC MIXR ADC1 Switch' 0"
	]

	Value {
		CapturePCM "hw:${CardId},0"
		CapturePriority 200
		CaptureMixerElem "STO1 ADC"
		CaptureVolume "STO1 ADC Capture Volume"
	}
}
```
</details>

reboot your device and now it works 🥳🥳🥳
![obraz](https://github.com/user-attachments/assets/87ea9ab6-b838-4fbb-bc60-7c3bef2612be)
![image](https://cdn.discordapp.com/emojis/643177264170926090.gif?size=48)

_Source. https://gitlab.com/postmarketOS/pmaports/-/issues/2510#note_1813888035_

## There is more

but we can go one step further

i figured i might as well as give ya sth from myself to this 

like getting rid of non existing headphones

![obraz](https://github.com/user-attachments/assets/7d7f38dc-aaa4-44c2-8ddc-59aeef317488)

so i looked at [this monster](https://github.com/hexdump0815/imagebuilder/blob/main/systems/chromebook_trogdor/extra-files/usr/share/alsa/ucm2/SC7180/HiFi.conf) where author just decided to just comment it out

### one bleblesh later 🛠️

we have a file [HiFi.conf.txt](https://github.com/user-attachments/files/17055968/HiFi.conf.txt) (i cannot upload it as just .conf because github)
<details>
<summary>file content</summary>

```
# Use case configuration for ALC5682+MAX98357A on SC7180

SectionVerb {
	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Speaker"

	Value {
		PlaybackChannels 4
		PlaybackPCM "hw:${CardId},1"
		PlaybackPriority 100
		PlaybackMixerElem "Speaker"
		PlaybackVolume "Speaker Playback Volume"
	}
}

#SectionDevice."Headphones" {
#	Comment "Headphones"
#
#	EnableSequence [
#		cset "name='HPOL Playback Switch' 1"
#		cset "name='HPOR Playback Switch' 1"
#		cset "name='Stereo1 DAC MIXL DAC L1 Switch' 1"
#		cset "name='Stereo1 DAC MIXR DAC R1 Switch' 1"
#	]
#
#	DisableSequence [
#		cset "name='HPOL Playback Switch' 0"
#		cset "name='HPOR Playback Switch' 0"
#		cset "name='Stereo1 DAC MIXL DAC L1 Switch' 0"
#		cset "name='Stereo1 DAC MIXR DAC R1 Switch' 0"
#	]
#
#	Value {
#		PlaybackPCM "hw:${CardId},0"
#		PlaybackPriority 200
#		PlaybackMasterElem "DAC1"
#		PlaybackMixerElem "Headphone"
#		PlaybackVolume "Headphone Playback Volume"
#	}
#}

SectionDevice."Mic" {
	Comment "Internal Microphone"

#	ConflictingDevice [
#		"Headset"
#	]

	EnableSequence [
		cset "name='IF1 01 ADC Swap Mux' 1"
		cset "name='Stereo1 ADC L2 Mux' 1"
		cset "name='Stereo1 ADC R2 Mux' 1"
		cset "name='Stereo1 ADC MIXL ADC2 Switch' 1"
		cset "name='Stereo1 ADC MIXR ADC2 Switch' 1"
	]

	DisableSequence [
		cset "name='Stereo1 ADC L2 Mux' 0"
		cset "name='Stereo1 ADC R2 Mux' 0"
		cset "name='Stereo1 ADC MIXL ADC2 Switch' 0"
		cset "name='Stereo1 ADC MIXR ADC2 Switch' 0"
	]

	Value {
		CapturePCM "hw:${CardId},0"
		CapturePriority 100
		CaptureMixerElem "STO1 ADC"
		CaptureVolume "STO1 ADC Capture Volume"
	}
}

#SectionDevice."Headset" {
#	Comment "Headset Microphone"
#
#	EnableSequence [
#		cset "name='IF1 01 ADC Swap Mux' 2"
#		cset "name='Stereo1 ADC L1 Mux' 1"
#		cset "name='Stereo1 ADC R1 Mux' 1"
#		cset "name='Stereo1 ADC MIXL ADC1 Switch' 1"
#		cset "name='Stereo1 ADC MIXR ADC1 Switch' 1"
#	]
#
#	DisableSequence [
#		cset "name='Stereo1 ADC L1 Mux' 0"
#		cset "name='Stereo1 ADC R1 Mux' 0"
#		cset "name='Stereo1 ADC MIXL ADC1 Switch' 0"
#		cset "name='Stereo1 ADC MIXR ADC1 Switch' 0"
#	]
#
#	Value {
#		CapturePCM "hw:${CardId},0"
#		CapturePriority 200
#		CaptureMixerElem "STO1 ADC"
#		CaptureVolume "STO1 ADC Capture Volume"
#	}
#}
```
</details>

again put it here ```/usr/share/alsa/ucm2/Qualcomm/sc7180/rt5682-max98357a/HiFi.conf``` ... now reboot

and it works 🎉🎉🎉🎈
![Zrzut ekranu z 2024-09-19 10-23-04](https://github.com/user-attachments/assets/9bab570b-87f9-4f50-b0f6-1df97add898c)

@hexdump0815 it's done (i think)
still in case there is any issue or update will leave the discussion open

**Comment by thenameisluk** [comment]
![obraz](https://github.com/user-attachments/assets/e6edbcf5-5923-448f-a98a-a980c7829751)
solving it is left as an exercise for the reader

**Comment by thenameisluk** [comment]
so i have figured out not perfect solution
by conflicting hdmi with speaker we can get it to configure only when available
```
# Use case configuration for ALC5682+MAX98357A on SC7180

SectionVerb {
	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Speaker"

	Value {
		PlaybackChannels 4
		PlaybackPCM "hw:${CardId},1"
		PlaybackPriority 100
		PlaybackMixerElem "Speaker"
		PlaybackVolume "Speaker Playback Volume"
	}
}

SectionDevice."Mic" {
	Comment "Internal Microphone"

	EnableSequence [
		cset "name='IF1 01 ADC Swap Mux' 1"
		cset "name='Stereo1 ADC L2 Mux' 1"
		cset "name='Stereo1 ADC R2 Mux' 1"
		cset "name='Stereo1 ADC MIXL ADC2 Switch' 1"
		cset "name='Stereo1 ADC MIXR ADC2 Switch' 1"
	]

	DisableSequence [
		cset "name='Stereo1 ADC L2 Mux' 0"
		cset "name='Stereo1 ADC R2 Mux' 0"
		cset "name='Stereo1 ADC MIXL ADC2 Switch' 0"
		cset "name='Stereo1 ADC MIXR ADC2 Switch' 0"
	]

	Value {
		CapturePCM "hw:${CardId},0"
		CapturePriority 100
		CaptureMixerElem "STO1 ADC"
		CaptureVolume "STO1 ADC Capture Volume"
	}
}

SectionDevice."HDMI" {
	Comment "HDMI"

#fixes the conflict
	ConflictingDevice [
		"Speaker"
	]

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},2"
		JackControl "sc7180-rt5682-max98357a-1mic HDMI Jack"
	}
	EnableSequence [
	]
	DisableSequence [
	]
}
```

meaning that when you plug in hdmi you just need to run ```systemctl --user restart pipewire``` for hdmi to get configured
and after unpluging run again for it to disappear from the device menu
![obraz](https://github.com/user-attachments/assets/27ba3f19-eb23-4c87-b8a5-ac310b9c6baa)

but it's not ideal

i was looking at the conditions but including these in the config just seam to break everything so idk

i know that unplugging and plugging in the devices triggers
```
node hw:0, #9 (0,0,0,HDMI Jack,0) VALUE
```
in ```sudo alsactl monitor``` but i have no idea how to use it

**Comment by thenameisluk** [comment]
the best i could come up with
if you ```systemctl --user restart pipewire``` while hdmi is plugged in or just start the computer with hdmi plugged in
it will not only configure it but also hide/unhide it from the menu when unpluggned/replugged
otherwise nope
```
# Use case configuration for ALC5682+MAX98357A on SC7180

SectionVerb {
	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Speaker"


	Value {
		PlaybackChannels 4
		PlaybackPCM "hw:${CardId},1"
		PlaybackPriority 100
		PlaybackMixerElem "Speaker"
		PlaybackVolume "Speaker Playback Volume"
	}
}

SectionDevice."Mic" {
	Comment "Internal Microphone"

	EnableSequence [
		cset "name='IF1 01 ADC Swap Mux' 1"
		cset "name='Stereo1 ADC L2 Mux' 1"
		cset "name='Stereo1 ADC R2 Mux' 1"
		cset "name='Stereo1 ADC MIXL ADC2 Switch' 1"
		cset "name='Stereo1 ADC MIXR ADC2 Switch' 1"
	]

	DisableSequence [
		cset "name='Stereo1 ADC L2 Mux' 0"
		cset "name='Stereo1 ADC R2 Mux' 0"
		cset "name='Stereo1 ADC MIXL ADC2 Switch' 0"
		cset "name='Stereo1 ADC MIXR ADC2 Switch' 0"
	]

	Value {
		CapturePCM "hw:${CardId},0"
		CapturePriority 100
		CaptureMixerElem "STO1 ADC"
		CaptureVolume "STO1 ADC Capture Volume"
	}
}

SectionDevice."HDMI" {
	Comment "HDMI Jack"
	
	ConflictingDevice [
		"Speaker"
	]

	EnableSequence [
	]

	DisableSequence [
	]

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},2"
		JackControl "HDMI Jack"
	}
}
```
unless you know any better just put it here ```/usr/share/alsa/ucm2/Qualcomm/sc7180/rt5682-max98357a/HiFi.conf``` and be happy it works

**Comment by thenameisluk** [comment]
just some notes for me
- lazor :
```
#
# Sound card
#
- card: 0
  id: sc7180rt5682max
  name: sc7180-rt5682-max98357a-1mic
  longname: sc7180-rt5682-max98357a-1mic
  driver_name: SC7180
  mixer_name: 
  components: 
  controls_count: 47
  pcm:
    - stream: PLAYBACK
      devices:
        - device: 0
          id: MultiMedia0 rt5682-aif1-0
          name: 
          subdevices:
            - subdevice: 0
              name: subdevice #0
        - device: 1
          id: MultiMedia1 HiFi-1
          name: 
          subdevices:
            - subdevice: 0
              name: subdevice #0
        - device: 2
          id: MultiMedia2 i2s-hifi-2
          name: 
          subdevices:
            - subdevice: 0
              name: subdevice #0
    - stream: CAPTURE
      devices:
        - device: 0
          id: MultiMedia0 rt5682-aif1-0
          name: 
          subdevices:
            - subdevice: 0
              name: subdevice #0
alsactl: rawmidi_device_list:105: snd_ctl_rawmidi_next_device
```
- homestar :
```
#
# Sound card
#
- card: 0
  id: sc7180rt5682max
  name: sc7180-rt5682-max98357a-1mic
  longname: sc7180-rt5682-max98357a-1mic
  driver_name: SC7180
  mixer_name: 
  components: 
  controls_count: 48
  pcm:
    - stream: PLAYBACK
      devices:
        - device: 0
          id: MultiMedia0 rt5682-aif1-0
          name: 
          subdevices:
            - subdevice: 0
              name: subdevice #0
        - device: 1
          id: MultiMedia1 multicodec-1
          name: 
          subdevices:
            - subdevice: 0
              name: subdevice #0
        - device: 2
          id: MultiMedia2 i2s-hifi-2
          name: 
          subdevices:
            - subdevice: 0
              name: subdevice #0
    - stream: CAPTURE
      devices:
        - device: 0
          id: MultiMedia0 rt5682-aif1-0
          name: 
          subdevices:
            - subdevice: 0
              name: subdevice #0
alsactl: rawmidi_device_list:105: snd_ctl_rawmidi_next_device
```
diff lazor homestar
```
11c11
<   controls_count: 47
---
>   controls_count: 48
22c22
<           id: MultiMedia1 HiFi-1
---
>           id: MultiMedia1 multicodec-1
```
in order to get the ucm upstream i need to make it work on both lazor and homestar
and i since lazor has headphone jack and homestar doesn't it might be tricky
